spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Honeylemonade/config-repast
          username: Honeylemonade
          password: Fmnmsqwe159852
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8888