server:
  port: 8084
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/repast_order?serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 159852
  jpa:
    generate-ddl: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoint:
    bus-refresh:
      enabled: true